### ISSUE TITLE
cannot use req.Header.Pid (type uint32) as type int in argument to sysutils.GetExecPathFromPID" on freebsd/amd64

### ISSUE THREAD

**Issue by cobaugh** [keybase/kbfs#1000]
Another type mismatch. Convering req.Pid to int gets kbfsfuse to compile the rest of the way.

**Comment by strib** [comment]
Thanks!  Put up #1001 to fix.  I confirmed this makes kbfsfuse compile with GOOS=freebsd (on linux).

@songgao points out that there will still be runtime issues on freebsd.  The specific one we know about, related to this issue, is that if you try to move a file between top-level folders (say between your private and public folders), you will see an error.  There may be other things lurking too.  If we have time we'll try to look at it soon, but if you notice anything else please let us know! Thanks for your help.

**Comment by cobaugh** [comment]
And with a little bit of effort to get the fuse kernel module loaded, I'm up and running!
