### ISSUE TITLE
Playing mp3 from kbfs

### ISSUE THREAD

**Issue by KeeganEad** [keybase/kbfs#1034]
Playing an mp3 file from inside a KBFS directory result in constantly repeated desktop notifications that the file is being decrypted.

OSX Client
File opened in VLC player.

![image](https://user-images.githubusercontent.com/26011894/27036633-7be0917c-4f53-11e7-9037-c2627526825d.png)

**Comment by strib** [comment]
This is intentional.  Sorry if you find it annoying, but we are trying to showcase the fact that encryption/decryption is happening, since the user can't otherwise tell.  We might dial this back or remove it in the future, but for now it's intentional.

**Comment by KeeganEad** [comment]
Okay, thanks for the information.  :)
