### ISSUE TITLE
Git helper: issue with accented characters?

### ISSUE THREAD

**Issue by gboudreau** [keybase/kbfs#1267]
I have files in a git repository with accented characters: `Amélie` for example.

I imported this repository into a Keybase git repository (from a gog repository, if that matters).

The problem is that git sees the files as new file. If I delete it, git sees the deleted file, and if a `git checkout .`, the file re-appears, and git still thinks it's new.

I'm pretty sure the issue is caused by how the accented character gets encoded.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	"Quatuor-Rhapsodie-2013-09-Am\303\251lie-150x150.jpg"

no changes added to commit (use "git add" and/or "git commit -a")

$ ls -1 | grep '09-Am.*150'
Quatuor-Rhapsodie-2013-09-Amélie-150x150.jpg

$ ls -1 | grep '09-Am.*150' | hexdump -C
00000000  51 75 61 74 75 6f 72 2d  52 68 61 70 73 6f 64 69  |Quatuor-Rhapsodi|
00000010  65 2d 32 30 31 33 2d 30  39 2d 41 6d 65 cc 81 6c  |e-2013-09-Ame..l|
00000020  69 65 2d 31 35 30 78 31  35 30 2e 6a 70 67 0a     |ie-150x150.jpg.|
0000002f
```
So the é character is actually 3 bytes: `65 cc 81`

```
$ rm "Quatuor-Rhapsodie-2013-09-Amélie-150x150.jpg"

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	deleted:    "Quatuor-Rhapsodie-2013-09-Ame\314\201lie-150x150.jpg"

no changes added to commit (use "git add" and/or "git commit -a")

$ git checkout .

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	"Quatuor-Rhapsodie-2013-09-Am\303\251lie-150x150.jpg"

no changes added to commit (use "git add" and/or "git commit -a")
```

I have not yet been able to reproduce in a test git repository...

**Comment by gboudreau** [comment]
I still can't reproduce with another empty repo, but maybe this will help:  
I noticed the file named is different when I checkout and when I delete it:

```
$ rm "Quatuor-Rhapsodie-2013-09-Amélie-150x150.jpg"
$ git status
	deleted:    "Quatuor-Rhapsodie-2013-09-Ame\314\201lie-150x150.jpg"
$ git checkout .
$ git status
	"Quatuor-Rhapsodie-2013-09-Am\303\251lie-150x150.jpg"
```

So it seems to be encoded as `e\314\201` in the git metadata, but when I checkout it, it is created as `\303\251`.

If it matters, I'm on mac OS 10.13 (High Sierra).
```
$ echo $LANG
en_CA.UTF-8
```

**Comment by gboudreau** [comment]
I resolved the issue with this command:
```
git config --global core.precomposeunicode false
```

**Comment by strib** [comment]
Hi, I don't think the git remote touches filenames at all.  From our perspective, we just see byte blobs that we store, we don't touch filenames or anything.  I suspect maybe the git commit was encoded by a client on a machine with different unicode settings?

**Comment by gboudreau** [comment]
Maybe, maybe. I guess those files could have been committed from a Linux host. Anyway, there is an easy way to fix it, so this can be closed, if you're sure this is not caused by Keybase' code. Cheers.
