### ISSUE TITLE
git ls-remote fails for empty repo

### ISSUE THREAD

**Issue by SevereOverfl0w** [keybase/kbfs#1325]
I believe the cause is empty repo, I get a different result on empty ssh/git repos for example.

```
$ git ls-remote keybase://team/myteam/test-repo
git-remote-keybase error: (1) stat : no such file or directory
git-remote-keybase error: (1) stat : no such file or directory
```

**Comment by SevereOverfl0w** [comment]
This error goes away if I simply make a local commit to the repo, _without_ pushing.

**Comment by strib** [comment]
Thanks for the report.  I can't repro it though. I tried this:

```sh
# Make empty remote repo
$ keybase git create test2
# Make empty local repo
$ mkdir test2
$ cd test2
$ git init
# Try ls-remote.
$ git ls-remote keybase://private/strib/test2
Initializing Keybase... done.
Syncing with Keybase... done.
Syncing encrypted data to Keybase: (100.00%) 9.47/9.47 KB... done.
$ echo $?
0
```

Is this different from the steps you took?  Also, what version of Keybase are you running, there was a similar bug on an older build a while back.  I can look at logs if you feel like doing a `keybase log send`.

**Comment by SevereOverfl0w** [comment]
I created the git repo through the gui.

I did not do mkdir/cd/git init before doing git ls-remote.

ID of log is ef424eddafe991198aa6d31c

**Comment by SevereOverfl0w** [comment]
I'm running on 1.0.34-20171027161021.a0eab0ba7 btw.

**Comment by strib** [comment]
Oh I see, the difference is you're not running it from within a local git repo.  I can track that down.  Thanks!

**Comment by strib** [comment]
#1327 fixes it for me.

**Comment by strib** [comment]
Should be working in the next release.  Thanks!
