### ISSUE TITLE
No drive K: on windows 

### ISSUE THREAD

**Issue by NobbZ** [keybase/kbfs#1338]
All of a sudden drive ``K:`` disappeared from my computer.

I'm not able to get it back by restarting keybase, the computer or even repair-installing keybase.

I do not want to revoke this workstation to be able to do a full re-install.

**Comment by maxtaco** [comment]
Sorry about that! @zanderz can you take a look?

**Comment by zanderz** [comment]
@NobbZ can you please issue `keybase log send` at the command line and post the log ID here?
Did anything else happen around the time of losing drive K:, such as installing antivirus software or some other filesystem driver?
Thanks.

**Comment by NobbZ** [comment]
The last time I used it on that windows box is about 4 weeks ago. Since then there were a couple of Keybase updates. I realized the missing drive only because I wanted to put away some text document. 

I'll check the logs tomorrow, today I can't get access to that machine anymore.

**Comment by NobbZ** [comment]
Things I roughly remember I have done were these:

* A couple of "clean boots" meaning deactivating most of services and autostarts, but I have reverted those and do full boots now.
* I removed a virusscanner completely since it caused my system to pause up to a minute sometimes. I have not yet installed a new one.

The log ID is `39e91ded96b0c0da3370bd1c`.

**Comment by NobbZ** [comment]
Today I realized the drive beeing back, I will close for now but keep an eye on it.
