### ISSUE TITLE
Lost 250 GB of Space

### ISSUE THREAD

**Issue by computerluca** [keybase/kbfs#1381]
After installing Keybase i noticed that my free space of the disk has decremented enormously.
So i run df -h and I noticed a new partition of 250 GB !!!!!!! and I lost 250 GB of space on the Disk.
I uninstalled keybase, but the space has not been reclaimed.

**Comment by strib** [comment]
That was not a new partition on your local drive. It is 250 GB of new space that we give you for free, that is stored in the cloud, not locally.

**Comment by computerluca** [comment]
And why if I run df-h i see new partition
/dev/fuse       250G  1,0K    250G   1% /keybase
and the root partition is decremented by 250 GB 
/dev/sda2       453G  371G     59G  87% /

**Comment by strib** [comment]
The partition is on `/dev/fuse`, not one of your hard drive devices.  I have no idea what is using the space on /dev/sda2, but Keybase is not the one using it. You can run `du -h -d 1 /` to figure out which subdirs are using the space.

**Comment by computerluca** [comment]
Thank you for the help!
