### ISSUE TITLE
kbfs with GoogleDrive

### ISSUE THREAD

**Issue by kazuhiko-hotta** [keybase/kbfs#1410]
Hi.

I bumped a problem related kbfs with GoogleDriveSync.

GoogleDrive can't work with kbfs, because GoogleDrive require plain filesystem.

See this screen shot blow. that image says it seems network filesystem.

![image](https://user-images.githubusercontent.com/11729756/34400628-c9b26f54-ebd6-11e7-9a01-fbef423f8f93.png)

and I wonder why kbfs hooks those directories? can I chose directories which I want to be encrypted.

**Comment by strib** [comment]
KBFS is only mounted at `/keybase`, it shouldn't interfere with any library directories.  I can't tell from the screenshot what Google Drive is trying to do, but you should be able to tell it to avoid the `/keybase` directory.

**Comment by kazuhiko-hotta** [comment]
Thanks for replying.
I tried to reproduce the issue but I couldn't make it.
now kbfs works normally.
