### ISSUE TITLE
KBFS filenames can cause issues for Windows users

### ISSUE THREAD

**Issue by Nitroretro** [keybase/kbfs#1435]
Hello!

I am using Linux, and I sent my friend (who is running Windows) a file called `HELLO_WORLD_-=[];',~!@#$%^&*()_+{}:"<>?.txt`. Since Windows doesn't support some of the characters that I have put in the filename, he reported that his Keybase client is now crashing among other things.

He's running **Windows 10**.

I suggest adding some kind of filename filter to prevent this. Thanks!

**EDIT:** The same thing MIGHT happen if you name a file `CON, PRN, AUX, CLOCK$, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9,
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9`, but I haven't tried it out.

**Comment by strib** [comment]
cc: @taruti @zanderz what do you guys think?

**Comment by zanderz** [comment]
I think it at least shouldn't crash! I'll try it too. Meanwhile, do we know which process is crashing?

**Comment by Nitroretro** [comment]
I wish, but that's all the info he gave me. If I get more info I'll post it here.

**Comment by strib** [comment]
Please ask him to run `keybase log send` from a terminal and mention the issue when asked for feedback, that should give us the info we need to debug.

**Comment by Nitroretro** [comment]
He doesn't wanna run it. He probably thinks it's malicious. I'm installing Windows 8.1 in order to recreate the issue myself. I'll get back with more info.

**Comment by zanderz** [comment]
this was a chat attachment? Placing a file named that from Mac in a shared folder and opening it on windows 10 doesn't cause any crashing for me

**Comment by taruti** [comment]
Testing on kbfsdokan does not reveal a crash.

**Comment by Nitroretro** [comment]
Shared folder. I finished installing 8.1, I'll download keybase on it and see if I can reproduce the issue.

**Comment by Nitroretro** [comment]
Unable to reproduce on Windows 8.1.

**Comment by taruti** [comment]
@Nitroretro closing this as unable to reproduce. Feel free to re-open if you or your friend stumble upon this again.
