### ISSUE TITLE
Please use ~/keybase

### ISSUE THREAD

**Issue by simonvanderveldt** [keybase/kbfs#1451]
Please consider using `~/keybase` instead of `/keybase`

There are several reasons for this:
- From #309: "The /keybase path is non-standard and violates both FHS and ~Arch's~ every distro's packaging guidelines"
- It's user specific data that's put within the global system, which is obviously not good
- It breaks ownership. Currently `/keybase` for me is owned by `root:root`, but `root` cannot do anything with that directory
- `/keybase` is not portable accross all operating systems anyway (i.e. it doesn't work on Windows)

Now I understand that it's nice and easy to just just send "Use something from `/keybase/team/someteam/somefile.ext` to someone else, but there must be other/better ways to keep stuff simple, like just sending `~/keybase/team/someteam/somefile.ext`, without violating basic Linux/UNIX specs/principles.

**Comment by strib** [comment]
Thanks for your feedback.  However the `kbfs` repo is not responsible for the mountpoint, that happens in the `client` repo under the packaging code, and we have several issues open over there tracking requests like this already.  We are actively working on ideas to fix this at the moment.  If you're running Linux, feel free to edit the `run_keybase` script to put the mountpoint wherever you like.  We'll have a more complete fix in the future.
