### ISSUE TITLE
keybase.pub is a little lag than files in local /keybase/public

### ISSUE THREAD

**Issue by yan12125** [keybase/kbfs#1458]
Description:

When I modify a file in /keybase/public, I need to wait for some time (usually < 1 second) to get the corresponding file on keybase.pub updated. Here's a testing script:
```python
# This script requires Python 3
import itertools
import time
import urllib.request

for i in itertools.count(1):
    print(i)
    with open('/keybase/public/yan12125/test.txt', 'w') as f:
        f.write(str(i))
    while True:
        print('req')
        req = urllib.request.urlopen('https://yan12125.keybase.pub/test.txt')
        remote = int(req.read().decode('ascii').strip())
        if remote == i:
            break
        print('remote={}, local={}'.format(remote, i))
    time.sleep(1)
```
A sample result after 5 iterations and hit Ctrl+C:
```
1
req
remote=2, local=1
req
2
req
remote=1, local=2
req
3
req
remote=2, local=3
req
4
req
remote=3, local=4
req
5
req
remote=4, local=5
req
```
As shown in the testing result, usually the first request to https://yan12125.keybase.pub does not match local file contents. Is it a limitation of FUSE, kbfs or the keybase.pub server? And how can I make sure files are correctly synced? I can use _sleep(n)_ for now, yet I'd like a more reliable solution.

**Comment by songgao** [comment]
`cat /keybase/public/.kbfs_status` should give you a `json` overview for that folder, including journal status. Once the journal is fully flushed, everything is on our server. But that doesn't mean the changes are reflected on keybase.pub instantly. There's another delay where keybase.pub needs to get notified about the latest update and it'll start using that. But since keybase.pub and KBFS servers are in the same AWS region, this should be fairly fast.

**Comment by strib** [comment]
It should be `cat /keybase/public/yan12125/.kbfs_status`.

**Comment by yan12125** [comment]
Thanks for prompt responses! I checked the ```.kbfs_status``` file and see there's a ```DirtyPaths``` field.  By polling ```DirtyPaths```, the lag is rare - only one mismatch in 100 iterations.

I guess the delay between AWS servers is inevitable? I may rethink my software architecture and make kbfs latency irrelevant. (You can close this ticket if the fix costs too much.)

**Comment by strib** [comment]
@yan12125: You need to see that both `DirtyPaths` (in-memory changes that haven't been flushed to disk yet) and `UnflushedPaths` (on-disk changes that haven't been flushed to the server yet) are empty.

**Comment by strib** [comment]
And yeah I think there will always be some lag in the keybase.pub getting updates from our servers -- you'd need control of the keybase.pub server to force it to fetch the newest data and wait for that to finish, as opposed to just polling for it.

**Comment by yan12125** [comment]
> You need to see that both DirtyPaths (in-memory changes that haven't been flushed to disk yet) and UnflushedPaths (on-disk changes that haven't been flushed to the server yet) are empty.

Thanks! With both checked, mismatches are gone.

**Comment by strib** [comment]
Great!
