### ISSUE TITLE
keybase.pub returns 404 for existing file (intermittently)

### ISSUE THREAD

**Issue by yan12125** [keybase/kbfs#1470]
For example: https://yan12125.keybase.pub/arch-repo/yan12125-testing/yan12125-testing.db is sometimes 200 and sometimes 404.

**Comment by maxtaco** [comment]
thx, we're on it!

**Comment by yan12125** [comment]
I got no more 404 errors for existing files. I presume this is fixed and can be closed?

**Comment by strib** [comment]
Yep thanks.
