### ISSUE TITLE
Please tag 1.0.42 corresponding to the client release

### ISSUE THREAD

**Issue by eli-schwartz** [keybase/kbfs#1487]
This would allow distros to package kbfsfuse alongside the keybase binaries.

**Comment by strib** [comment]
Just tagged v1.0.44 (we had a couple buggy releases here on the client side, but this should match the latest, non-buggy client release tag).

**Comment by eli-schwartz** [comment]
Thanks, I've updated keybase and added a kbfs package to the Arch Linux repos. Now the only thing I still need to figure out how to package is the electron app and we'll have everything. \o/

**Comment by eli-schwartz** [comment]
v1.0.46 is out without the corresponding kbfs release...
