### ISSUE TITLE
File not overwritten by >file under Cygwin

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/kbfs#1494]
I use Cygwin on windows, tjek this:

```
$ printf "A\nB\n">t

$ cat t
A
B

$ printf "Z\n">t

$ cat t
Z
B
```

**Comment by strib** [comment]
@taruti some issue with Truncate in dokan under cygwin?  Can you please take a quick look?

**Comment by taruti** [comment]
This is specific to cygwin/mingwin/msys, e.g. cmd exe works correctly. The redirection does a bunch of fs calls but ends up doing an FILE_OPEN_IF instead of e.g. FILE_OVERWRITE_IF. Investigating further and will fix.

Thank you @mortenkjarulff for an issue so easy to reproduce.
