### ISSUE TITLE
Cannot open KeepassXC databases from KBFS folders on Windows

### ISSUE THREAD

**Issue by rask** [keybase/kbfs#1521]
Hello!

I'm not sure if this issue is related to KBFS or KeepassXC directly so I'm submitting issues to both. I created a KeepassXC issue already: https://github.com/keepassxreboot/keepassxc/issues/1753

So, in essence, I would like to store my KeepassXC database inside a private KBFS folder. This has worked fine on Ubuntu PCs and the database is operable between them.

Today I installed Keybase and KeepassXC on my Windows 7 and ran into an issue with loading a KeepassXC database from my private KBFS folder. The KBFS drive and folders work well when browsing with Windows Explorer, but I can't find the K: drive when opening a database in the KeepassXC UI.

Is this related to how the KBFS is implemented so K: is not visible in default Windows filesystem dialogs or should KBFS be visible on those as well? Or would the KeepassXC client need some extra feature to KBFS is visible for it?

**Comment by strib** [comment]
@rask hmm that's super weird.  I don't know of any special thing you have to do to get K:\ to show up for other applications.

I saw the comment on your other issue about `QFileDialog`.  A search shows me [this](https://askubuntu.com/questions/714765/some-open-file-dialogs-dont-see-other-partitions), which implies that the developer might have to do something to add a sidebar to the dialog?  Also LMMS/lmms#1058 mentions something similar, but in that case there is a text field which takes arbitrary paths...

Anyway, I don't _think_ there's anything more we can be doing, but @taruti or @zanderz might know more?

**Comment by rask** [comment]
Yeah QtDialog was mentioned, I'm currently looking for some other apps with QtDialogs to see if those can or cannot see KBFS disks.

**Comment by rask** [comment]
Okay, false alarm on this. Windows being Windows and the KBFS appeared to the KeepassXC dialog normally after a few reboots. https://github.com/keepassxreboot/keepassxc/issues/1753#issuecomment-374337924

**Comment by zanderz** [comment]
I didn't see my kbfs letter when using KeepassXC, but I did when using LiteIDE. It could be a matter of different options used with the Win32 apis when presenting a comctl32 file picker, just guessing.
