### ISSUE TITLE
Is a Standalone or Selfhosted Version out of the box possible?

### ISSUE THREAD

**Issue by cyberpunkbln** [keybase/kbfs#1524]
Hello,

i like keybase and kbfs but i don't want the cloudstorage and the socialnetworkcomponents. I want only the abbility to store my files in a private dir with kbfs or use a selfhosted-keybase/kbfs server.

Is that out of the box possible?

thx

**Comment by strib** [comment]
It is not currently possible, and not planned.  Our server side code is closed source and would need to reimplemented by someone else.  Sorry!

**Comment by cyberpunkbln** [comment]
No Problem, then i will have a look at this project when i need the cloud-functions;).
