### ISSUE TITLE
Keybase says I accessed a folder with a user who I didn't share the folder with

### ISSUE THREAD

**Issue by Lucky225** [keybase/kbfs#1538]
Any time I access ANY folder in K:\private (for the first time, after keybase initially starts), it says I accessed a folder with user rayjoha. Accessing additional folders doesn't seem to do anything, but regardless of which folder I access, the first one I access gives this pop up. I just installed a keybase update so I figured now would be a good time to see if that's still happening after starting it after the update, sure enough it did, so I got a printscreen of it:

![image](https://user-images.githubusercontent.com/3251120/38279138-31a69498-375c-11e8-894f-513373cc98c0.png)

**Comment by strib** [comment]
A file from that folder is probably in a "recently used" list somewhere in Windows.  You can either find and clear that list, or you can just follow the user to avoid future popups.  Note that you can follow the user locally with `keybase follow -l rayjoha` from a terminal, so it doesn't show up in your public list of followees.

**Comment by Lucky225** [comment]
Thanks, I was just looking at #10042 in the client issues (figured it would have been here since it's file system related) and I think you're correct, I'm about to restart after following the user and see if that clears the issue.

**Comment by Lucky225** [comment]
That worked. Apologies didn't want to open a known issue with resolution, I did search first I swear :)
