### ISSUE TITLE
KBFS works on FreeBSD; should we mention it somewhere?

### ISSUE THREAD

**Issue by 0mp** [keybase/kbfs#1576]
Hi,

I'm happily using KBFS on FreeBSD. Do you think it is worth adding a note about it to README.md (and any other related documents)?

The current setup process is pretty straightforward. I've written down all the required steps and troubleshooting hints on the FreeBSD wiki [here](https://wiki.freebsd.org/Ports/security/kbfs).

Cheers

**Comment by maxtaco** [comment]
Sure, sounds like a good idea!

cc @strib

**Comment by strib** [comment]
Thanks @0mp and @maxtaco.  I put up PR #1580 for this.
