### ISSUE TITLE
Public folder no longer available

### ISSUE THREAD

**Issue by airthom** [keybase/kbfs#1578]
The app on Mac and on my android phone still show the folder with the files in it... however the folder no longer available from the webpage.  No changes have been made (that I'm aware of).

macOS Sierra - 10.12.6 -- Keybase 1.0.47-20180511010500+206cfc714b 

Pixel XL - 8.1.0  -- Keybase 1.0.47-2018058204103+64468e0574

**Comment by airthom** [comment]
Ran keybase log send ... log id is 45028d8700e1add7eac04c1c

**Comment by strib** [comment]
Should be fixed now.

**Comment by ghalfacree** [comment]
Just got a notification that my keybase.pub proof has broken, and sure enough it's 404ing again. Log sent under ID 1aa747146ed7273c22807a1c.

**Comment by strib** [comment]
Should be fixed now, we had a bug in our linux client (which also powers keybase.pub) that refused to read folders last written by devices that have been revoked a long time ago.

**Comment by ghalfacree** [comment]
I can confirm that it's working again - thanks, @strib!
