### ISSUE TITLE
Client IO Error, Server: block does not exist

### ISSUE THREAD

**Issue by donovan** [keybase/kbfs#1602]
Hi there.

I have an issue where a file in my private directory is unreadable on all devices. I can stat or ls the file in question but if I do something that requires reading the file (eg md5sum, file) I get an Input/output error. If I check `~/.cache/keybase/keybase.kbfs.log` I can see errors like `Read error=EIO: Server: block does not exist` that correspond to me attempting to read the file.

This occurred where a device that was writing the file had intermittent connectivity issues (wifi was flapping as the wifi gateway was being rebooted).

My questions are:

1. Is there any way to retrieve this file or revert it to previous readable version (I'm guessing no)?
2. Is there anything I can do to avoid this in the future (short of don't write to kbfs while the network is flaky)?
3. Will Offline mode for kbfs #1592 help mitigate this issue?
4. Is this a common issue or did I get unlucky and hit an edge case?

To anyone reading this: this is a reminder to think of kbfs as a way to share the same files on multiple devices  and _not_ a way to backup files _to_ multiple devices. If you corrupt a file on one device it will be faithfully corrupted everywhere. If you care about data stored in kbfs you should back it up elsewhere.

**Comment by strib** [comment]
@donovan Sorry for the bad experience.  I can help debug and answer your questions if you run `keybase log send` and post the resulting log ID here.

**Comment by donovan** [comment]
Hi strib

No problem, I love the keybase and was able to recover the file in question.

Does it matter which device I run `keybase log send` on? Should it be the device where I wrote the file or can it be any of my devices?

Thanks

**Comment by strib** [comment]
Any device that tried to read the file would be a good start, but I'll probably eventually ask you for one from the writing device as well, if possible.

**Comment by donovan** [comment]
Ok, I am not near those devices currently, I'tll be sometime in the next 24 hours.

**Comment by donovan** [comment]
Hi

There is little prospect of me doing anything more with this as I recovered and moved on. Going to close this issue.
