### ISSUE TITLE
Cannot access `/keybase`

### ISSUE THREAD

**Issue by petergarbers** [keybase/kbfs#1608]
VERSION:
   2.0.0-20180604163023+f899a761a7

```
> % cd /keybase
cd: no such file or directory: /keybase
```

I have read through https://github.com/keybase/kbfs/issues/1368 and am unable to find the button to install the kernel extension inside of the file / folders tab in the GUI

**Comment by strib** [comment]
@petergarbers what operating system are you running?  If you're on mac or Windows, look in the "Files" section of the GUI, or in the settings under "Files".

**Comment by strib** [comment]
Ah ok, you already have it checked it in the settings.  This is a known bug that we'll fix soon.  You need to quit the Keybase app and relaunch it to get the Finder integration after you set it on osx.

**Comment by petergarbers** [comment]
Hi @strib 
I have gone as far as to restart my machine, to no avail.

**Comment by strib** [comment]
@petergarbers ok, if you do `keybase log send` and post the resulting log ID here, I can take a look.

**Comment by petergarbers** [comment]
Reinstalling seems to have fixed it! Thanks
