### ISSUE TITLE
Transparent access to contents of private/public directories?

### ISSUE THREAD

**Issue by mbklein** [keybase/kbfs#162]
If I write something to `/keybase/public/mbklein@github/foo.txt`, it gets signed. When I read it back out, I get the plaintext that I (and others) can trust is signed. Is there a way to access the cryptographically signed version off the server directly?

Same goes for stuff in `public` – I'd like to be able to write to the directory and then send someone the resulting encrypted file to decrypt by other means.

**Comment by strib** [comment]
Thanks for the suggestion!  Please see the existing open ticket on this: keybase/client#2250.
