### ISSUE TITLE
Weird behaviour: "X and Y are the same file" or "input file is output file"

### ISSUE THREAD

**Issue by pyllyukko** [keybase/kbfs#1666]
I stumbled upon weird situation with KBFS. It claims that file X and file Y are the same file, when they aren't.

Here's a script to reproduce the behaviour (modeled from [this script](http://www.slackware.com/~alien/tools/gen_repos_files.sh)):

```
#!/bin/bash
DIR="/keybase/public/pyllyukko/test"
FILE1="test-file-1.txt"
FILE2="test-file-2.txt"
mkdir -v "${DIR}" 2>/dev/null
pushd "${DIR}" 2>/dev/null || exit 1
function do_stuff() {
  echo '[*] removing FILE1'
  rm -v "${DIR}/${FILE1}" &>/dev/null
  echo '[*] creating FILE1'
  cat <<-EOT >"${DIR}/${FILE1}"
	FILE1
	EOT
  echo '[*] creating FILE2'
  echo "FILE2" 1>"${DIR}/${FILE2}"
  echo '[*] FILE2 >> FILE1'
  cat "${DIR}/${FILE2}" >> "${DIR}/${FILE1}"
  echo '[*] FILE1 -> FILE2'
  mv -f  "${DIR}/${FILE1}" "${DIR}/${FILE2}"
}
for i in {1..2}
do
  echo "round #${i}"
  do_stuff
  echo -n $'\n'
done
```

What I would expect to happen (when ```DIR``` is e.g. ```/tmp/test```):

```
mkdir: created directory '/tmp/test'
/tmp/test ~
round #1
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
[*] FILE1 -> FILE2

round #2
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
[*] FILE1 -> FILE2
```

What actually happens with KBFS:

```
mkdir: created directory '/keybase/public/pyllyukko/test'
/keybase/public/pyllyukko/test ~
round #1
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
[*] FILE1 -> FILE2

round #2
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
cat: /keybase/public/pyllyukko/test/test-file-2.txt: input file is output file
[*] FILE1 -> FILE2
mv: '/keybase/public/pyllyukko/test/test-file-1.txt' and '/keybase/public/pyllyukko/test/test-file-2.txt' are the same file
```

Any idea what's going on here? Thanks.

**Comment by strib** [comment]
@pyllyukko What OS is this on?  I can't reproduce it on Linux, in my personal private home dir:

```
$ /tmp/x.sh 
/keybase/private/strib/tmp /keybase/private/strib/tmp
round #1
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
[*] FILE1 -> FILE2

round #2
[*] removing FILE1
[*] creating FILE1
[*] creating FILE2
[*] FILE2 >> FILE1
[*] FILE1 -> FILE2

```

Maybe macOS?  I don't have one of those handy to test right now, but if you do a `keybase log send` after running the script I might be able to dig a little bit.  Does seem weird.

**Comment by strib** [comment]
Thanks, logs: 14f2ac828dc1f3a58dc26c1c.  I will look into it in more detail tomorrow.

**Comment by strib** [comment]
@pyllyukko looks like you're running a version of Keybase/KBFS from December 2017.  Any chance I could get you to upgrade and try again?  Off the top of my head I can't think of a related bug that we've fixed since then, but it's worth a try and even if it doesn't work, it'll make debugging easier for me.

**Comment by pyllyukko** [comment]
> @pyllyukko looks like you're running a version of Keybase/KBFS from December 2017. Any chance I could get you to upgrade and try again? Off the top of my head I can't think of a related bug that we've fixed since then, but it's worth a try and even if it doesn't work, it'll make debugging easier for me.

Whoops! So I was. I kept upgrading the Keybase package itself, but the FUSE stuff (kbfs package) was older. Now it doesn't seem to do it anymore, although now my mount keeps dying after a while, but that's another issue.

Sorry for the false alarm.
