### ISSUE TITLE
fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab

### ISSUE THREAD

**Issue by miztroh2** [keybase/kbfs#1730]
I've installed the keybase-gui package for Arch.  Everything in the GUI works just find (logging in, adding computer, browsing files, chatting, etc.).  However, the file system integration is broken.  It complains about a missing /etc/mtab entry.  My understanding is that this file should not be edited manually.  Please advise.

![screenshot from 2018-08-09 10-36-36](https://user-images.githubusercontent.com/40702740/43909594-51da164a-9bc0-11e8-8732-ef8f9196433d.png)

**Comment by strib** [comment]
That `fusermount` command shouldn't be fatal, it's just trying to unmount an existing mount if there is one, before it tries to mount the new one.  The error code should be ignored (it's prefixed with a `-` in the service definition).

If the FS really isn't working, there's probably something else going on later in the logs.  You can try `keybase log send` and we can see if it's obvious from there.

**Comment by miztroh2** [comment]
I just sent my logs: 8006b217a7e06d16c361701c.

**Comment by strib** [comment]
The error is:

```
stat /run/user/1000/keybase/kbfs: no such file or directory
```

Looks like you might have the environment variable `$XDG_RUNTIME_DIR` set to `/run/user/1000`, but the OS didn't actually create that directory for you.  Perhaps you are using `su` or `sudo` in an unusual way, and don't have a proper login session.

You can always change the mount directory with something like:

```sh
keybase config set mountdir /home/you/keybase
```

**Comment by miztroh2** [comment]
/run/user/1000/keybase/kbfs is the location I've come to expect.  The /run/user/1000/keybase folder got created just fine.

![screenshot from 2018-08-09 11-17-22](https://user-images.githubusercontent.com/40702740/43911799-ff7079b6-9bc5-11e8-8665-b5ae9ece978b.png)

Is setting the keybase mountdir to /home/me/keybase the recommended approach?  Before switching from keybase-bin to keybase-gui, the "official" package was still using /run/user/1000/keybase.

**Comment by strib** [comment]
@miztroh2 did you start it with `run_keybase`?  Or were you trying to start it purely via the service stuff?  For now, `run_keybase` is required.

**Comment by miztroh2** [comment]
run_keybase doesn't seem to be included with the keybase-gui package (or its dependencies keybase and kbfs).

https://www.archlinux.org/packages/community/x86_64/keybase-gui/

**Comment by strib** [comment]
I'm not familiar with that package.  @eli-schwartz ?

**Comment by eli-schwartz** [comment]
#1669

**Comment by strib** [comment]
That's obviously not done yet.  I thought the package included `run_keybase`.  Did you take it out?

**Comment by eli-schwartz** [comment]
The `run_keybase` script is not very useful considering that it hardcodes the binary to start in /opt, whereas I package it in /usr/share and start it via `/usr/bin/electron`. And it also tries to run a redirector which I don't install, which runs as setuid root.

I'd need to reimplement the script, which I have not done since the only thing it currently does not do (to my knowledge) is `mkdir -p "$(keybase config get -d -b mountdir)"` -- hence my issue #1655 and corresponding PR.

If you create the directory by hand this works fine though.

**Comment by miztroh2** [comment]
I stopped _keybase.gui_, _keybase_, and _kbfs_ user services.  I then manually created the _kbfs_ folder inside of _/run/user/1000/keybase_ and restarted said services.  Everything checked out and I could access the kbfs mount through GNOME Files.  However, once I restarted my computer, the kbfs directory was gone.  Not sure what would cause that.  Any ideas?

**Comment by eli-schwartz** [comment]
`/run` is a tmpfs and will be recreated from scratch at boot.

BTW my mountpoint is still set to `~/.local/share/keybase/fs` (you can use `keybase config set mountdir /path/to/custom/mountdir` to relocate it)

**Comment by miztroh2** [comment]
OK, I've updated my mountdir to the one you specified and that seems to work, even after reboot.  Thanks!
