### ISSUE TITLE
android: git-remote-keybase stderr dup error

### ISSUE THREAD

**Issue by philips** [keybase/kbfs#1775]
I am testing git-remote-keybase after porting to android's termux (https://github.com/termux/termux-packages/pull/2804) and I am getting the following error:

```
$ git init
Initialized empty Git repository in /data/data/com.termux/files/home/foo/.git/
$ git remote add origin keybase://private/philips/foo
$ vim README.md
$ git push origin master
git-remote-keybase error: (1) Duplicating stderr is not supported on this operating system
```

xref #1231 
cc @songgao

**Comment by strib** [comment]
We'll need an implementation of something like `syscall.Dup` that works on Android, like this: https://github.com/keybase/kbfs/blob/ed63bec510192b0739c519293d0133a6205bd281/stderrutils/dup_stderr_nix.go

Maybe this one just works, I really don't know.  If you test it and it does, I'm happy to drop the `!android` from the build tags.

**Comment by songgao** [comment]
@philips No test for this; sorry! The `dup` call is so that the remote helper can write terminal output. Could you please try this branch `songgao/add-android-dup-stderr`? If it builds, and a `git clone` works fine, and you see `Initializing Keybase...` in the stderr output when `git` is running, then I think it's fine.

**Comment by philips** [comment]
Fixed in https://github.com/keybase/kbfs/pull/1776

**Comment by songgao** [comment]
Thanks Brandon!

**Comment by philips** [comment]
Fix merged. Closing. 

If you would cut a release with this fix I would appreciate it :)

**Comment by strib** [comment]
> If you would cut a release with this fix I would appreciate it :)

Hopefully we'll have a Linux release out within a day or so, our buildbot has been flaky lately.  Other platforms, including Android, probably next week.

**Comment by philips** [comment]
I just need a tag to build from and a release tar.gz. binaries aren't
necessary.

**Comment by strib** [comment]
Ah ok.  We usually only tag when we do the big releases for all platforms (i.e., probably next week).  But we're not stingy with tags.  If you want one sooner, I can just make one (like say `2.5.0.build-for-android` or something weird like that), especially if you only need a kbfs tag.

**Comment by strib** [comment]
@philips: https://github.com/keybase/kbfs/releases/tag/initial-git-on-android

**Comment by philips** [comment]
thanks! PR up https://github.com/termux/termux-packages/pull/2811
