### ISSUE TITLE
Truncate file on Linux dosn't always work

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/kbfs#1829]
This is hard to prove, as I can't replicate, but here is what I think I saw.

I have Solid Explorer on my android phone connected via SFTP to my Linux. Today I wanted to delete the very last character of a file (the last character was not \n. Solid Explorer gave me a green checkmark when I saved the file. However, the file seemed unchanged. I did try some times (5 I think). When I instead replaced the last character with a \n, the file was changed.

On the same Linux, some days ago, I did
```
cat a b>c
```
which would make c much smaller. But, the part of c that should have been deleted, was instead replaced with binary zeros.

I bit like https://github.com/keybase/kbfs/issues/1494

**Comment by strib** [comment]
Hmm, I can't seem to reproduce this on Linux.  I've tried taking an 11K file, deleting the final newline, and `cat`ing it over the existing file, and it always works as expected.

Maybe you can send logs after this happens to you?  Or provide some example files (or file sizes) on which this happens reliably?

**Comment by mortenkjarulff** [comment]
f02c006b45a1e846a25b251c

Will send a video

**Comment by mortenkjarulff** [comment]
Forget this. If I copy the file to my home, same thing happen, so it's not keybase 👍

**Comment by strib** [comment]
Ok cool, maybe that explains the Solid Explorer issue (from our perspective).

But is there still a remaining issue with directly using Linux?  (Your `cat a b>c` example from above.)  Is that reproducible for you?

**Comment by mortenkjarulff** [comment]
Hi.

I can't reproduce.

Morten
