### ISSUE TITLE
Filesystems permissions are funny

### ISSUE THREAD

**Issue by crosser** [keybase/kbfs#212]
keybase fs installed from the deb on Ubuntu xenial:
Version: 1.0.16-20160802173443.d99d9c7

Subdirectories of the filesystem are shown as owned by root, and not writable to the user.

```
crosser@pccross:~$ ls -lR /keybase/*/crosser
/keybase/private/crosser:
total 0
drwx------ 1 root root 158 Aug  3 11:53 chris
drwx------ 1 root root 156 Aug  3 11:44 jno

/keybase/private/crosser/chris:
total 0
-rw-r--r-- 1 root root 105 Aug  3 11:53 oh-nice.txt

/keybase/private/crosser/jno:
total 0
-rw-r--r-- 1 root root 26 Aug  3 11:44 hello.txt

/keybase/public/crosser:
total 0
-rw-r--r-- 1 root root 40 Aug  3 11:48 greetings.txt
```

However, they are writable (at least those belonging to the user).
This is confusing. It would be better if filesystem permissions at least vaguely reflected the actual read- and writeability. Obviously "foreign" directories cannot be properly owned, they may stay owned by `root` or by `nobody`.

(Sorry for the mess with this ticket: I accidentally opened it before I wrote the description.)

**Comment by crosser** [comment]
reopen, with proper description now, sorry!

**Comment by strib** [comment]
Sorry for the very delayed response, but current releases of KBFS should do this correctly now.
