### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by gabx** [keybase/kbfs#288]
OS: Archlinux 64
[keybase-bin 1.0.17](https://aur.archlinux.org/packages/keybase-bin) 
-------------
$kbfsfuse --help
Usage of kbfsfuse:
  -bserver string
    	host:port of the block server (default "bserver.kbfs.keybase.io:443")
......
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53eff7]

goroutine 1 [running]:
panic(0xe21580, 0xc420010150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/keybase/kbfs/libkbfs.SizeFlag.String(0x0, 0xe835a0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/flag_size.go:23 +0x37
flag.isZeroValue(0xc420239b00, 0xc4202691e8, 0x5, 0xfa0e2e)
	/usr/local/go/src/flag/flag.go:393 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc420239b00)
	/usr/local/go/src/flag/flag.go:467 +0x1d5
flag.(*FlagSet).VisitAll(0xc420074060, 0xc42022b8a8)
	/usr/local/go/src/flag/flag.go:323 +0x67
flag.(*FlagSet).PrintDefaults(0xc420074060)
	/usr/local/go/src/flag/flag.go:476 +0x46
flag.PrintDefaults()
	/usr/local/go/src/flag/flag.go:499 +0x2d
flag.glob..func1()
	/usr/local/go/src/flag/flag.go:523 +0xce
flag.(*FlagSet).usage(0xc420074060)
	/usr/local/go/src/flag/flag.go:823 +0x42
flag.(*FlagSet).parseOne(0xc420074060, 0x0, 0x0, 0x13a52453c000)
	/usr/local/go/src/flag/flag.go:870 +0xb4c
flag.(*FlagSet).Parse(0xc420074060, 0xc42008e070, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/flag/flag.go:915 +0x60
flag.Parse()
	/usr/local/go/src/flag/flag.go:943 +0x72
main.start(0x4060db)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsfuse/main.go:68 +0x76
main.main()
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/kbfsfuse/main.go:111 +0x36

**Comment by taruti** [comment]
This was fixed by 973ef74b907b748dc38097935b966c0cd5bf153b, thanks for the report!
