### ISSUE TITLE
kbfs public documents for 2 (or more) people

### ISSUE THREAD

**Issue by zeridon** [keybase/kbfs#317]
Hello Team,

try the following:

````
cd /keybase/public/<name>,<othername>
echo "some text" > test.txt
````

Ask othername to check if he sees this
Ask some other guy to check your public space

Is this a file that is public
Is this a file that is private
Should this be visible in /keybase/public/name
Should this be visible in /keybase/public/othername
Is this an expected behaviour

**Comment by strib** [comment]
Hi @zeridon -- KBFS paths are global, so everyone sees the same path.  Therefore, if you put a file in `/keybase/public/<name>,<othername>` on your device, it will be visible in `/keybase/public/<name>,<othername>` on your friend's device as well.

Anything under `/keybase/public` can be read by anyone in the world.

If you want to share something privately with your friend, use `/keybase/private/<name>,<othername>`.  Does that answer your question?

**Comment by zeridon** [comment]
Partially yes. I had the expectation that under public you can publish only under your prefix only. Might be good to explain in the docs that this is not the case

**Comment by strib** [comment]
Have you read https://keybase.io/docs/kbfs/understanding_kbfs?

**Comment by zeridon** [comment]
Thank you strib. That explains it quite nicely. I was not aware of this page. Thanks for pointing it out.
