### ISSUE TITLE
Creating files using windows client

### ISSUE THREAD

**Issue by arnonuem** [keybase/kbfs#322]
Using Windows 7 Professional with client: Keybase GUI Version: 1.0.17-20160822153555+692af12
When entering private/username or public/username and using context menu / new i can only create a new folder but not a new file. It is only possible to create a file in a temporary location on windows and then copy that file into the desired directory.

**Comment by strib** [comment]
Hi @arnonuem: as far as I know this should work but I haven't tested it recently.  Could you please reproduce, then do a `keybase log send` and let us know the log ID to show us the error?

cc: @taruti

**Comment by arnonuem** [comment]
How can i reproduce when its just all about showing the NEW entry in the context menu. The new entry is just not there.

**Comment by taruti** [comment]
Can confirm this - thanks for the report. Writing files will still work.

Implementing a nicer `GetFileSecurity` should help for this, will add an internal issue for that feature.

**Comment by viamyeye** [comment]
Hi All, 

Client:  1.0.17-20160822152935+692af12
Service: 1.0.17-20160822152935+692af12

The KBFS is mounting as K:\ on my system (Win 7 Pro SP1) as expected.

I can only create folders via File Explorer (Right Click > New > Folder)

I've also tried echoing out to a file via cmd.exe which works.

e.g. 

K:
cd public\jubes
echo "this is a test" > test.txt

As a side note, attempting to cd to K: using cmder doesn't work and I receive "The system cannot find the path specified.".

**Comment by taruti** [comment]
@viamyeye The right-click thing is known and we are fixing it very soon.

Please open a new issue to the cmder issue.

Thanks for taking care of reporting bugs!
