### ISSUE TITLE
Can you add more people to a share after is made?

### ISSUE THREAD

**Issue by ChrisFernandez** [keybase/kbfs#335]
I have a share with /keybase/private/cfernandez,person1,person2,person3,person4   works well but can I add more people after I already created it?

**Comment by strib** [comment]
No, we don't support that.  One of our tenets is that the full path to a share is always valid.  In the future though we will be supporting named groups as a participant in a shared folder, and you will be able to add or remove people from the group.

For now, I'm afraid you'll need to manually copy the data to a new share if you want to add new people.
