### ISSUE TITLE
Windows - Unable to access K:\ using cmder

### ISSUE THREAD

**Issue by viamyeye** [keybase/kbfs#352]
Client: 1.0.17-20160822152935+692af12
Service: 1.0.17-20160822152935+692af12

Following on from [#322](https://github.com/keybase/kbfs/issues/322)

I'm unable to run the following commands using [cmder](http://cmder.net/):

K:
cd K:
cd K:\
cd K:\
K:\public\jubes
K:\private\jubes

I've also raised this as an issue with the cmder guys [#1096](https://github.com/cmderdev/cmder/issues/1096)

**Comment by viamyeye** [comment]
If I run cmder without administrator privileges i'm able to access K:\. Linked to [353](https://github.com/keybase/kbfs/issues/353)

**Comment by taruti** [comment]
See the explanation on #353 - this is not specific to cmder but to blocking different users.

I'll close this one if ok?
