### ISSUE TITLE
save backup via bup to kbfs dir throwing an error on close

### ISSUE THREAD

**Issue by soulware** [keybase/kbfs#368]
Originally issue here - https://github.com/keybase/keybase-issues/issues/2578

Posting here as it is kbfs related - 

I am attempting to setup bup (https://bup.github.io/) against a BUP_DIR on a kbfs mount at `/keybase/private/<username>/bup`. 

Something is not happy in the bup git internals when attempting to run `bup save` -

```
Reading index: 7, done.
Saving: 100.00% (2/2k, 7/7 files), done.    
Traceback (most recent call last): 
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/cmd/bup-save", line 460, in <module>
    w.close()  # must close before we can update the ref
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/bup/git.py", line 790, in close
    return self._end(run_midx=run_midx)
  File "/usr/local/Cellar/bup/0.28.1/lib/bup/bup/git.py", line 776, in _end
    os.fsync(self.parentfd)
OSError: [Errno 5] Input/output error
```

Is this a known limitation in kbfs?

**Comment by strib** [comment]
There's a discussion over at keybase/keybase-issues#2578.
