### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by jhellenthal** [keybase/kbfs#379]
I upgraded to macOS and initially the kbfs was not working. After deleting the application install and installing from a download on keybase.io I was able to then again utilize the kbfs kext. A short while later the following day I believe there was an update that was taken under the hood and it is no longer available to use. Not sure what is going on here when it previously was working. What kind of an ETA do we have on fixing this and how can I help ? I need this working for work purposes desperately

**Comment by maxtaco** [comment]
We're blocked on this: https://github.com/osxfuse/osxfuse/issues/314

**Comment by gabriel** [comment]
You might be able to force the KBFS install.. via:

```
keybase install --components=kbfs --force=true
```

We have a fix coming shortly for Sierra but might be a few days..

**Comment by strib** [comment]
Sierra is now supported in the most recent builds.
