### ISSUE TITLE
Dual Boot Delima

### ISSUE THREAD

**Issue by jabarihunt** [keybase/kbfs#390]
I'm migrating a laptop from Windows to Linux (Kubuntu to be exact).  I'm currently dual booting, but once everything has been migrated and setup I'm going to kill the Windows partitions and expand my /home partition.

I originally setup keybase on the Windows partition, along with a paper key.  I lost the original key, but created a second.  I logged into Linux and installed keybase.  Initially, I used my keybase passphrase to login.  It told me that I needed to rekey my private folder using my first device.  Since I'm dual booting and can't run them at the same time, I tried using my paper key instead.  It failed, saying that the "Paper key is empty".

So, I deprovisioned the device (on Linux), restarted keybase (keybase ctl start/stop), and logged in again, but this time using the paper key.  I still get the same error when attempting to rekey my private folder.

Any ideas?  Log ID: cb5e441196fa8e46eca3e21c

**Comment by jabarihunt** [comment]
BTW - I don't have many files in my Windows private folder.  I can copy them to a drive and migrate them that way.  If I do that, and then deprovision the Windows machine, will I still need to rekey???

**Comment by strib** [comment]
@jabarihunt --sorry for the delay, we don't look at the issues list in this repo very much (`keybase/client` sees more action).

I've never heard of a "Paper key is empty" error before.  @patrickxb @maxtaco does that mean anything to you?

If everything is properly keyed for your paper key, then you don't have to worry about keeping your Windows partition around.  If the paper key is busted for some reason, there's a problem.

However, once you have provisioned your new device, simply booting back into Windows and running Keybase should be enough for KBFS to rekey all your existing folders to the new device key.  Then you can try going back to Linux and seeing if it worked.

**Comment by jabarihunt** [comment]
Thanks for the reply @strib!

I've been going back and fourth between the two for the last week.  Every time I boot the Linux distro I get prompted to rekey.  I believe both machines would have to be running at the same time, which is impossible since I'm dual booting.

That said, The paper key issue has me stumped.

If I can't find a solution by the weekend I'll provision my wife's laptop and let it do the rekeying, then deprovision it.

**Comment by patrickxb** [comment]
The empty paper key error occurs when no words are entered at a paper key prompt.

@jabarihunt I assume you are typing your paper key into a GUI window?  

I'm not aware of any issues with that code but will check with the desktop team.

**Comment by strib** [comment]
Hmm, @jabarihunt could you do a `keybase log send` from your Window partition and let us know the ID?  I can't guess why your Windows KBFS instance isn't rekeying for you.

I assume you've actually tried (and failed) to access the folder on Linux?  I'm wondering if it could be an incorrect rekey prompt.

**Comment by jabarihunt** [comment]
@patrickxb Yes, when I boot up my Linux partition is immediately prompts me.  It lists the machines that can do a rekey and has a button that spawns a new dialog asking for the paper key.  I enter my paper key there, that's when I get the error.

@strib Correct, whenever I attempt to access my private folder in Linux it fails.
**LOG ID (Windows Partition):** _a4a810180603dee4379e841c_

**Comment by strib** [comment]
Ok thanks @jabarihunt.  Does like it might be useful for us to have a `log send` from your Linux partition too when you get a chance, showing an attempt to enter your paper key.

**Comment by patrickxb** [comment]
I can see the paper key attempts on the original log.

**Comment by jabarihunt** [comment]
@strib I put it in my original post.  I can send a fresh one if you need me to.
**Log ID (Linux Partition):** _cb5e441196fa8e46eca3e21c_

**Comment by patrickxb** [comment]
@jabarihunt the desktop team is going to look into the empty paper key issue.  I created an internal ticket.  Will update you as it progresses.  Sorry for the issue.

**Comment by jabarihunt** [comment]
Thank you, I really appreciate it!

**Comment by strib** [comment]
(Oops, sorry, I forgot there was already a Linux log send.)

@jabarihunt -- it looks like KBFS hasn't run on your Windows partition since 9/22, and it seems like the Keybase service isn't running either (there's no status).  That would explain why Windows isn't rekeying for you.  Does it look to you like it's running in Windows?

**Comment by jabarihunt** [comment]
I can access my folders.  I'm going to kill it in the system tray and restart it now.  I'll post results...

**Comment by jabarihunt** [comment]
When I restarted it, the Keybase screen opened and said that it's "Loading...".  It seems to be stuck there though.  I do recal being prompted for an update not to long ago.  It seems to go well, but looks can be deceiving.

**Comment by jabarihunt** [comment]
...and I CAN NOT access more folders (correction from earlier).

**Comment by strib** [comment]
Ah.  @zanderz @taruti, looks like we might have a Windows upgrade failure here.  Can you please take a look?

**Comment by jabarihunt** [comment]
I logged in via the CLI, then started the desktop app.  It's now running.  `keybase rekey status` produces:

```
C:\Users\Jabari\AppData\Roaming\Keybase>keybase rekey status
TLFs need rekeying:
private/jabari

Devices that can rekey:
desktop Neo
```

**Comment by jabarihunt** [comment]
OK, I think I finally figured it out...

After looking at @strib's comment about a Windows upgrade failure, I ran `keybase update check`.  While it was running I was prompted to do a "repair".  After that ran, it immediately began rekeying!

**Comment by strib** [comment]
Huzzah!

**Comment by strib** [comment]
(Oops, didn't mean to close, there's still the empty paper key issue.)

**Comment by jabarihunt** [comment]
Thanks for reminding me!  Hmmm...so should I create a new paper key and deprovision the existing paper key?

**Comment by strib** [comment]
I wouldn't do that yet, seems like it could be a client bug rather than an issue with your paper key.

**Comment by patrickxb** [comment]
Your paper key probably fine. Think it is a GUI bug.

**Comment by jabarihunt** [comment]
@patrickxb Any way to test for sure?

**Comment by patrickxb** [comment]
Do you see it in 'keybase device list'?

**Comment by jabarihunt** [comment]
Yes...all three are listed:

```
C:\Users\Jabari\AppData\Roaming\Keybase>keybase device list
Name                         Type         ID                                 Created                Last Used
==========                   ==========   ==========                         ==========             ==========
Kneo                         desktop      f3c624f6a4cb6a6523781f378827db18   2016 Sep 29 22:49:01   2016 Oct 5 08:14:32
Neo                          desktop      2bb12c4d4ea290c511bafa1398d32018   2016 Aug 25 23:40:58   2016 Oct 7 12:45:21
Paper Key (actor staff...)   backup       5005d0e99c472ce36e809fc97fdf8c18   2016 Sep 28 21:19:55   2016 Sep 29 22:49:01
```

**Comment by jabarihunt** [comment]
Everything seems to be working great now.  I'm going to go ahead and close this issue unless anyone wants me to test something on my end...
