### ISSUE TITLE
SuperDuper clone not working after upgrading to macOS Sierra 

### ISSUE THREAD

**Issue by ebello** [keybase/kbfs#391]
Hi, trying to run SuperDuper after upgrading to Sierra gives me the following error:

```
Error | SDCopy: Failed to copy extended attributes to directory /Volumes/.../keybase
Error | : Device not configured
```

Is there a workaround until kbfs is supported in Sierra?

**Comment by strib** [comment]
Did you also upgrade your Keybase to the version that disables KBFS?  i.e., is KBFS actually running?  It should be turned off for Sierra until we release a version with the fix (which is coming soon).

I don't recommend cloning `/keybase` though, if that's what you're doing.  It will try to sync all the data in all the folders you've ever looked at.

**Comment by ebello** [comment]
I'm running Version 1.0.17-20160922174631+f87e42c (1.0.17-20160922174631+f87e42c). When I open the Keybase app I do get the warning about Sierra.

Thanks for the suggestion about not cloning `/keybase`. I was able to do that by editing the current copy script in SuperDuper and ignoring the folder, and the clone is running again.
