### ISSUE TITLE
Docs/source for keybase.pub?

### ISSUE THREAD

**Issue by kevinSuttle** [keybase/kbfs#408]
Would love to dig into how this actually works.

**Comment by strib** [comment]
The keybase.pub site is open source, but the part that interfaces with kbfs is simple: the webserver just mounts `/keybase` and serves/reads data directly via the KBFS mount.  Does that help?  Do you have other specific questions?

**Comment by cjb** [comment]
(@strib, think you meant to say is *not* open source.)

**Comment by strib** [comment]
Derp, edited.

**Comment by kevinSuttle** [comment]
Right, so the main page mentions "it serves Markdown", but can you go into more specifics? 

Which MD rendering processor?
Can it handle JS?
What kind of server? 
Etc.

**Comment by strib** [comment]
Oh I see.  @malgorithms can you provide some details?

**Comment by kevinSuttle** [comment]
Awesome! Thanks @malgorithms!
