### ISSUE TITLE
Heavy filesystem access causes displayport driver to restart

### ISSUE THREAD

**Issue by Diggsey** [keybase/kbfs#425]
Installed kbfs on a microsoft surface pro 4 - since then my external monitor connected via displayport flashes black frequently, as though the driver is crashing and being restarted. It seems to correspond to heavy file-system access, although not necessarily to the `K:` drive.

Unfortunately there's nothing obvious in the event log corresponding to those times.

**Comment by maxtaco** [comment]
Cc: @taruti and @zanderz

**Comment by taruti** [comment]
Hi, can you share the output of `driverquery` and do a `keybase log send`?

**Comment by zanderz** [comment]
Subsequent updates have included improved drivers, is this still an issue?

**Comment by Diggsey** [comment]
I haven't had the issue in a while - I'll close this and reopen if it occurs again.
