### ISSUE TITLE
Keybase client won't install on Windows 10

### ISSUE THREAD

**Issue by Omegas** [keybase/kbfs#434]
I'm attempting to install the Keybase client on Windows 10 version 1607, build 14393 (x64). I download and run keybase_setup_386.exe and the installer starts. When I click Install, I briefly see the text "initializing" and then the installer disappears. Keybase is added to the list of installed programs in Control Panel but the icon does not appear in the taskbar and I can't see any directory created under Program Files either.  I tried to run the installer with the Run As Administrator option and without it but that didn't change anything. The installation log file is attached.
[Keybase_20161018143903_log.txt](https://github.com/keybase/kbfs/files/536305/Keybase_20161018143903_log.txt)

**Comment by maxtaco** [comment]
Cc: @zanderz

**Comment by zanderz** [comment]
Has a more recent version been successfully installed? If not, can you attach `Keybase_*_log.txt`, where the name can also include `KeybasePrograms` or `Dokan` ?

**Comment by taruti** [comment]
@Omegas this should work with more recent versions, please reopen this issue if this reoccurs.
