### ISSUE TITLE
https://keybase.pub/<user> not serving kbfs file

### ISSUE THREAD

**Issue by vdice** [keybase/kbfs#456]
Using the keybase client (`Client:  1.0.17-20160930202009+0229d49
Service: 1.0.17-20160930202009+0229d49`) on Mac OSX El Capitan 10.11.16, 

I've added `keybase.txt` to `/keybase/public/vdice`  and have confirmed that it exists:

```
$ ls /keybase/public/vdice/
keybase.txt

$ cat /keybase/public/vdice/keybase.txt
==================================================================
https://keybase.io/vdice
--------------------------------------------------------------------
<rest of file omitted>
```

Yet, the file does not appear to be served on https://keybase.pub/vdice/ : 
![keybase_pub_vdice](https://cloud.githubusercontent.com/assets/9322017/19661994/22798500-99f3-11e6-9ad7-c44a94282167.png)

**Comment by strib** [comment]
Hi @vdice -- looks like you recently reset your account, and there's a known bug with KBFS (and keybase.pub in that case) where it continues to cache your pre-reset public folder.  I'll restart keybase.pub for you, which should pick it up.

**Comment by strib** [comment]
Ok, looks good to me now.  Please close this if you agree.

**Comment by vdice** [comment]
Ah, thank you @strib!  Looks great; closing.
