### ISSUE TITLE
kbfs frozen, cannot manipulate with files

### ISSUE THREAD

**Issue by Limeth** [keybase/kbfs#620]
It used to work, then, when I was uploading a larger amount of files, something made it stop working.
Now I can't use the kbfs at all, I can't even `cd` into my public directory.

**Comment by strib** [comment]
Can you please do a `keybase log send` and let us know the resulting log ID?  Thanks.

**Comment by Limeth** [comment]
@strib `7fac560793d413d82313871c` Thanks for a quick response.

**Comment by strib** [comment]
It seems like your local device key hasn't been unlocked.  Maybe you pressed cancel on a passphrase entry dialogue?  (Or maybe there is a popup window you haven't noticed somewhere?)

If not, maybe try an explicit `keybase unlock` (or `keybase logout` followed by `keybase login`) and see if that helps?

**Comment by Limeth** [comment]
When I restarted the system earlier, I could see a plain white window without decoration with the keybase icon. I closed it. I can access the keybase application from the system tray just fine, though.
I tried all of `keybase unlock/logout/login`, they all freeze and I have to interrupt it using `ctrl+c`.
I wanted to send another log, but now even the `keybase log send` command is frozen, after I typed "YES".

**Comment by Limeth** [comment]
Oh, seems like another plain white window appeared. That might be blocking keybase from functioning.

**Comment by Limeth** [comment]
Ran `killall keybase` and restarted `keybase log send`, if that helps. `8048851fa0ba201a0258de1c`

**Comment by strib** [comment]
cc @cjb @gabriel for plain white pinentry windows. Sorry for the inconvenience!

**Comment by strib** [comment]
@Limeth by the way, `keybase unlock` takes a `--stdin` parameter, letting you type your passphrase in the terminal instead of a GUI window (or letting you pipe it in from a file).  Not sure if that will solve your issue but it's worth a try.

**Comment by Limeth** [comment]
Running `keybase unlock` (with or without `--stdin`) gives me this error:
```
▶ ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory
```

**Comment by gabriel** [comment]
The blank pinentry screen was fixed in a recent build, you can try the latest here:
https://prerelease.keybase.io/darwin/Keybase-1.0.18-20161227210312%2B1d6f524.dmg

The `keybase` command line currently only works if Keybase.app is running, better messaging on that in PR here:
https://github.com/keybase/client/pull/5203

**Comment by gabriel** [comment]
(deleted previous comment since this is linux)

@oconnor663 Do we have a recent linux build with this fix?

**Comment by oconnor663** [comment]
@gabriel a new build went out on Linux [about two hours](https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/index.html) after your comment yesterday.

**Comment by Limeth** [comment]
Updated keybase, everything seems to be working again.
