### ISSUE TITLE
Deleting folder for "files before account reset"

### ISSUE THREAD

**Issue by sebastianbauer** [keybase/kbfs#661]
I did an account reset and had one test file in my private kbfs folder. Now there is a folder with "files before account reset". Those files should be rekeyed, what's not possible.

How to delete such a folder? It seems I just can hide it.

Thanks

**Comment by strib** [comment]
Deleting it from your favorites list, either with `rmdir` or through the GUI app, is the only option right now.

If you're worried about other people being able to access the files from the reset folder, the Keybase servers will only serve that data to writer on the folder.  So, for example, if you're worried about your public folder from before the reset, no one will be able to see that data but you.

If you're worried about reclaiming your quota, let us know and we can take care of that another way for now.

**Comment by sebastianbauer** [comment]
Thank you for clarification. No worry about the quota. I just will wait until it's possible to delete such a folder. Thank you.

**Comment by bardiharborow** [comment]
@strib has any progress been made on a more satisfactory resolution?

**Comment by strib** [comment]
No this hasn't been a priority.  You can just remove it from view with `rmdir`.  If there's a quota issue let me know and we can figure something out, or if there's some specific issue you're worried about let me know.
