### ISSUE TITLE
Is there a way to encrypt for multiple users from command line?

### ISSUE THREAD

**Issue by Engelberg** [keybase/kbfs#774]
I want to mimic what kbfs does to a shared private folder, but encrypt the file to be stored elsewhere, so that it can be decrypted by multiple keybase users.

**Comment by strib** [comment]
Yes, see `keybase encrypt --help`.  It's not exactly the same as KBFS though, since it won't re-encrypt the file when the users add new devices later.

**Comment by Engelberg** [comment]
I tried that, and it implies that you can, but when I do `keybase encrypt name1,name2,name3 -i filename.txt` I get an error saying `Unexpected OR operator`, which suggests you can't do multiple names.

**Comment by cjb** [comment]
@Engelberg I think it's `keybase encrypt -i filename.txt name1 name2 name3`.

**Comment by jzila** [comment]
@Engelberg: did @cjb's solution resolve your issue?

**Comment by Engelberg** [comment]
Yes. Thanks.
