### ISSUE TITLE
Password no longer required on Windows

### ISSUE THREAD

**Issue by Engelberg** [keybase/kbfs#932]
I've noticed recently that the Windows keybase client automatically logs in to keybase upon startup, fully connecting me to my private directories, without prompting for a password.  It used to prompt me for a password every time I started up the computer.  Is there a way to get back to the old behavior?

**Comment by strib** [comment]
Thanks for the report.  Would you mind filing this over in keybase/client instead?  It's not KBFS specific, and the folks here don't know how to answer it.
